# Generated by Django 2.2.9 on 2019-12-21 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TW', 'Twitter'), ('FB', 'Facebook')], max_length=2)),
                ('token', models.CharField(max_length=100)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TW', 'Twitter'), ('FB', 'Facebook')], max_length=2)),
                ('origin_id', models.CharField(db_index=True, max_length=50)),
                ('interest', models.PositiveIntegerField(null=True)),
                ('picture', models.URLField(max_length=250, null=True)),
                ('account_name', models.CharField(max_length=50, null=True)),
                ('last_update', models.DateTimeField(db_index=True, null=True)),
                ('update_error_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('type', 'origin_id')},
            },
        ),
        migrations.CreateModel(
            name='BrokenFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TW', 'Twitter'), ('FB', 'Facebook')], max_length=2)),
                ('origin_id', models.CharField(db_index=True, max_length=100)),
                ('account_name', models.CharField(max_length=100, null=True)),
                ('check_time', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('type', 'origin_id')},
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('type', models.CharField(max_length=30)),
                ('sub_type', models.CharField(max_length=30, null=True)),
                ('created_time', models.DateTimeField(db_index=True)),
                ('origin_id', models.CharField(db_index=True, max_length=50)),
                ('origin_data', models.TextField(help_text='Raw dump of all data from source', null=True)),
                ('interest', models.PositiveIntegerField(null=True)),
                ('picture', models.URLField(max_length=350, null=True)),
                ('share_link', models.URLField(max_length=350, null=True)),
                ('share_title', models.CharField(max_length=250, null=True)),
                ('share_caption', models.CharField(max_length=600, null=True)),
                ('share_description', models.TextField(null=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Feed')),
            ],
            options={
                'ordering': ['-created_time'],
                'unique_together': {('feed', 'origin_id')},
            },
        ),
    ]
